INSERT INTO user (user_name, email, password, role)
VALUES ('admin1', 'admin1@example.com', '$2a$10$someHashedPassword1', 'ADMIN'),
       ('contributor1', 'contributor1@example.com', '$2a$10$someHashedPassword2', 'CONTRIBUTOR'),
       ('contributor2', 'contributor2@example.com', '$2a$10$someHashedPassword3', 'CONTRIBUTOR'),
       ('user1', 'user1@example.com', '$2a$10$someHashedPassword4', 'USER'),
       ('user2', 'user2@example.com', '$2a$10$someHashedPassword5', 'USER'),
       ('user3', 'user3@example.com', '$2a$10$someHashedPassword6', 'USER'),
       ('user4', 'user4@example.com', '$2a$10$someHashedPassword7', 'USER'),
       ('user5', 'user5@example.com', '$2a$10$someHashedPassword8', 'USER'),
       ('user6', 'user6@example.com', '$2a$10$someHashedPassword9', 'USER'),
       ('user7', 'user7@example.com', '$2a$10$someHashedPassword10', 'USER');

INSERT INTO tag (tag_name)
VALUES ('Java'),
       ('Spring'),
       ('Programmation'),
       ('Backend'),
       ('Frontend'),
       ('Base de données'),
       ('API'),
       ('Sécurité'),
       ('DevOps'),
       ('Algorithmes');


INSERT INTO article (title, body, user_id)
VALUES ('Introduction à Spring Boot', 'Contenu de l''article sur Spring Boot...', 2),
       ('Bonnes pratiques en Java', 'Contenu sur les bonnes pratiques...', 2),
       ('Créer une API REST', 'Contenu sur la création d''une API REST...', 3),
       ('Sécurité avec Spring Security', 'Contenu sur Spring Security...', 1),
       ('Gestion des erreurs en Java', 'Contenu sur la gestion des erreurs...', 2),
       ('Hibernate vs JDBC', 'Comparaison entre Hibernate et JDBC...', 3),
       ('Les Design Patterns', 'Contenu sur les Design Patterns...', 1),
       ('Docker pour les devs', 'Contenu sur Docker...', 2),
       ('Optimiser ses requêtes SQL', 'Contenu sur l''optimisation SQL...', 3),
       ('Les tests unitaires', 'Contenu sur les tests unitaires...', 1),
       ('Git et GitHub', 'Contenu sur Git et GitHub...', 2),
       ('Les streams en Java', 'Contenu sur les streams...', 3),
       ('Spring Data JPA', 'Contenu sur Spring Data JPA...', 1),
       ('Créer un microservice', 'Contenu sur les microservices...', 2),
       ('Les annotations en Java', 'Contenu sur les annotations...', 3),
       ('Les collections en Java', 'Contenu sur les collections...', 1),
       ('Les exceptions en Java', 'Contenu sur les exceptions...', 2),
       ('Les interfaces fonctionnelles', 'Contenu sur les interfaces fonctionnelles...', 3),
       ('Les lambdas en Java', 'Contenu sur les lambdas...', 1),
       ('Les optionals en Java', 'Contenu sur les optionals...', 2),
       ('Les records en Java', 'Contenu sur les records...', 3);

-- Insertion de 20 lignes dans article_tag
INSERT INTO `article_tag`(`article_id`, `tag_id`)
VALUES (43, 1),
       (43, 2),
       (44, 3),
       (44, 4),
       (45, 5),
       (45, 6),
       (46, 7),
       (46, 8),
       (47, 9),
       (47, 10),
       (48, 1),
       (48, 3),
       (49, 2),
       (49, 5),
       (50, 4),
       (50, 7),
       (51, 6),
       (51, 9),
       (52, 8),
       (52, 10);